import type { LucideIcon } from 'lucide-react';
import {
  Beef,
  Soup,
  CookingPot,
  Coffee,
  Beer,
  CakeSlice,
  ShoppingCart,
  ShoppingBag,
  Shirt,
  Footprints,
  Gem,
  Gift,
  House,
  Bed,
  ReceiptText,
  Lightbulb,
  Smartphone,
  Laptop,
  Wifi,
  CarTaxiFront,
  Fuel,
  Plane,
  Bus,
  TrainFront,
  Bike,
  Hospital,
  Pill,
  Gamepad2,
  Clapperboard,
  Music,
  Library,
  Dog,
  Dumbbell,
  Scissors,
  Brush,
  Banknote,
  CreditCard,
  Landmark,
  TrendingUp,
  GraduationCap,
  ToyBrick,
  Droplet,
  Wrench,
  ShoppingBasket,
  CircleDollarSign,
  JapaneseYen,
  TreePalm,
  Monitor,
  Folder,
  Tag,
  CupSoda,
  Wine,
  Martini,
  GlassWater,
  Pizza,
  IceCreamCone,
  Cookie,
  Popsicle,
  Popcorn,
  TrainFrontTunnel,
  TramFront,
  Luggage,
  Utensils,
  Croissant,
  PartyPopper,
  Handbag,
  Motorbike,
} from 'lucide-react';

// Maps each picker emoji to its lucide equivalent. Emoji left out here (tea 🍵, champagne 🍾,
// dress 👗, won 🇰🇷) have no clean lucide glyph and fall back to the emoji itself — lucide lacks
// these where phosphor has them. Keyed by emoji, so a category's stored emoji maps straight through.
export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  '🍔': Beef,
  '🍜': Soup,
  '🍲': CookingPot,
  '☕': Coffee,
  '🍺': Beer,
  '🍰': CakeSlice,
  '🛒': ShoppingCart,
  '🛍️': ShoppingBag,
  '👕': Shirt,
  '👟': Footprints,
  '💍': Gem,
  '🎁': Gift,
  '🏠': House,
  '🏨': Bed,
  '🧾': ReceiptText,
  '💡': Lightbulb,
  '📱': Smartphone,
  '💻': Laptop,
  '📶': Wifi,
  '🚕': CarTaxiFront,
  '⛽': Fuel,
  '✈️': Plane,
  '🚌': Bus,
  '🚆': TrainFront,
  '🛵': Bike,
  '🏥': Hospital,
  '💊': Pill,
  '🎮': Gamepad2,
  '🎬': Clapperboard,
  '🎵': Music,
  '📚': Library,
  '🐶': Dog,
  '🏋️': Dumbbell,
  '💇': Scissors,
  '🧹': Brush,
  '💰': Banknote,
  '💳': CreditCard,
  '🏦': Landmark,
  '📈': TrendingUp,
  '🎓': GraduationCap,
  '🧸': ToyBrick,
  '🚰': Droplet,
  '🔧': Wrench,
  '🧺': ShoppingBasket,
  '🖥️': Monitor,
  '📁': Folder,
  '🏝️': TreePalm,
  '💲': CircleDollarSign,
  '💴': JapaneseYen,
  '🏷️': Tag,
  '🥤': CupSoda,
  '🍷': Wine,
  '🍸': Martini,
  '🥃': GlassWater,
  '🍕': Pizza,
  '🍦': IceCreamCone,
  '🍪': Cookie,
  '🍭': Popsicle,
  '🍿': Popcorn,
  '🚈': TrainFrontTunnel,
  '🚊': TramFront,
  '🧳': Luggage,
  '🍱': Utensils,
  '🍞': Croissant,
  '🍻': Beer,
  '🥂': PartyPopper,
  '👜': Handbag,
  '🏍️': Motorbike,
};
