// The /ssr entry ships icons built with forwardRef only — no IconContext/useContext — so they render
// in React Server Components (the category & add-expense pages are RSC). The default entry would throw
// there. We pass size/color explicitly, so the dropped context defaults cost us nothing. The `Icon`
// TYPE comes from the main entry (type-only import — erased at build, no runtime, no hooks).
import type { Icon } from '@phosphor-icons/react';
import {
  Hamburger,
  BowlFood,
  ForkKnife,
  Coffee,
  BeerBottle,
  Cake,
  ShoppingCart,
  ShoppingBag,
  TShirt,
  Sneaker,
  Diamond,
  Gift,
  House,
  Bed,
  Receipt,
  Lightbulb,
  DeviceMobile,
  Laptop,
  WifiHigh,
  Taxi,
  GasPump,
  AirplaneTilt,
  Bus,
  Train,
  Moped,
  FirstAid,
  Pill,
  GameController,
  FilmSlate,
  MusicNotes,
  Books,
  Dog,
  Barbell,
  Scissors,
  Broom,
  Money,
  CreditCard,
  Bank,
  ChartLineUp,
  GraduationCap,
  Drop,
  Wrench,
  Bag,
  Basket,
  BeerStein,
  Cheers,
  CurrencyCircleDollar,
  CurrencyJpy,
  CurrencyKrw,
  Dress,
  Island,
  DesktopTower,
  Folder,
} from '@phosphor-icons/react/ssr';

// Phosphor equivalents for each picker emoji. Phosphor covers the food/beauty specifics lucide
// lacks (Hamburger, Sneaker, Lipstick, Moped, TeddyBear), so this map is fuller. Keyed by emoji.
export const PHOSPHOR_ICONS: Record<string, Icon> = {
  '🍔': Hamburger,
  '🍜': BowlFood,
  '🍱': ForkKnife,
  '☕': Coffee,
  '🍺': BeerBottle,
  '🍰': Cake,
  '🛒': ShoppingCart,
  '🛍️': ShoppingBag,
  '👕': TShirt,
  '👟': Sneaker,
  '💍': Diamond,
  '🎁': Gift,
  '🏠': House,
  '🏨': Bed,
  '🧾': Receipt,
  '💡': Lightbulb,
  '📱': DeviceMobile,
  '💻': Laptop,
  '📶': WifiHigh,
  '🚕': Taxi,
  '⛽': GasPump,
  '✈️': AirplaneTilt,
  '🚌': Bus,
  '🚆': Train,
  '🛵': Moped,
  '🏥': FirstAid,
  '💊': Pill,
  '🎮': GameController,
  '🎬': FilmSlate,
  '🎵': MusicNotes,
  '📚': Books,
  '🐶': Dog,
  '🏋️': Barbell,
  '💇': Scissors,
  '🧹': Broom,
  '💰': Money,
  '💳': CreditCard,
  '🏦': Bank,
  '📈': ChartLineUp,
  '🎓': GraduationCap,
  '🚰': Drop,
  '🔧': Wrench,
  '🧺': Basket,
  '👜': Bag,
  '👗': Dress,
  '🍻': BeerStein,
  '🥂': Cheers,
  '🖥️': DesktopTower,
  '📁': Folder,
  '🏝️': Island,
  '💲': CurrencyCircleDollar,
  '💴': CurrencyJpy,
  '🇰🇷': CurrencyKrw,
};
