import type { LucideIcon } from 'lucide-react';
import {
  Beef,
  Soup,
  Coffee,
  Beer,
  CakeSlice,
  ShoppingCart,
  ShoppingBag,
  Shirt,
  Footprints,
  Gem,
  Gift,
  House,
  Bed,
  ReceiptText,
  Lightbulb,
  Smartphone,
  Laptop,
  Wifi,
  CarTaxiFront,
  Fuel,
  Plane,
  Bus,
  TrainFront,
  Bike,
  Hospital,
  Pill,
  Gamepad2,
  Clapperboard,
  Music,
  Library,
  Dog,
  Dumbbell,
  Scissors,
  Brush,
  Banknote,
  CreditCard,
  Landmark,
  TrendingUp,
  GraduationCap,
  ToyBrick,
  Droplet,
  Wrench,
} from 'lucide-react';

// Maps each picker emoji to its lucide equivalent. Emoji left out here (bento 🍱, makeup 💄,
// nails 💅) have no clean lucide glyph and fall back to the emoji itself — the food/beauty gap the
// live comparison showed. Keyed by emoji so category_meta needs no re-keying.
export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  '🍔': Beef,
  '🍜': Soup,
  '☕': Coffee,
  '🍺': Beer,
  '🍰': CakeSlice,
  '🛒': ShoppingCart,
  '🛍️': ShoppingBag,
  '👕': Shirt,
  '👟': Footprints,
  '💍': Gem,
  '🎁': Gift,
  '🏠': House,
  '🏨': Bed,
  '🧾': ReceiptText,
  '💡': Lightbulb,
  '📱': Smartphone,
  '💻': Laptop,
  '📶': Wifi,
  '🚕': CarTaxiFront,
  '⛽': Fuel,
  '✈️': Plane,
  '🚌': Bus,
  '🚆': TrainFront,
  '🛵': Bike,
  '🏥': Hospital,
  '💊': Pill,
  '🎮': Gamepad2,
  '🎬': Clapperboard,
  '🎵': Music,
  '📚': Library,
  '🐶': Dog,
  '🏋️': Dumbbell,
  '💇': Scissors,
  '🧹': Brush,
  '💰': Banknote,
  '💳': CreditCard,
  '🏦': Landmark,
  '📈': TrendingUp,
  '🎓': GraduationCap,
  '🧸': ToyBrick,
  '🚰': Droplet,
  '🔧': Wrench,
};
