// Ambient module for .mjs specifiers TypeScript can't resolve as a real file. TS ambient
// declarations reject any pattern containing "/" as a "relative module name" (TS2436), so a
// path-scoped declaration for '/sqlite3/sqlite3.mjs' isn't possible — only the bare '*.mjs'
// extension wildcard is. This codebase has exactly one unresolvable .mjs specifier: the
// self-hosted sqlite3 build (public/sqlite3/sqlite3.mjs, regenerated by scripts/copy-sqlite3.mjs),
// loaded at runtime via a turbopackIgnore'd dynamic import in worker.ts.
// NOTE: this file must have NO top-level import/export statement. A `declare module` block only
// augments the global ambient module map when its containing file is a script, not a module — add
// one top-level `import` here and this wildcard silently stops matching for every OTHER file in the
// program (it still typechecks locally, which makes the breakage easy to miss). Reference outside
// types via the inline `import('pkg').Type` query below instead.
// ponytail: if a second unresolvable .mjs import is ever added elsewhere, it would incorrectly
// inherit this shape too — narrow to a path-specific pattern (or split wildcards) if that happens.
declare module '*.mjs' {
  const sqlite3InitModule: (opts?: {
    locateFile?: (file: string) => string;
  }) => Promise<import('@sqlite.org/sqlite-wasm').Sqlite3Static>;
  export default sqlite3InitModule;
}
